requires 'perl' => 'v5.40.0';
requires "Mojolicious::Plugin::HTMX";
requires 'App::Sqitch';
requires 'Crypt::Passphrase';
requires 'Crypt::Passphrase::Argon2';
requires 'Crypt::Passphrase::Bcrypt';
requires 'Mojo::Pg';
requires 'Mojolicious';
requires 'Object::Pad';
requires 'YAML::XS';
requires 'Test::PostgreSQL';
