version: '3.8'

services:
  registry:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MOJO_MODE=production
      - DB_URL=postgresql://postgres:password@db:5432/registry
      - REGISTRY_SECRET=local-dev-secret-change-in-production
      - PORT=5000
    depends_on:
      - db
      - worker
    volumes:
      - ./storage:/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build: .
    environment:
      - MOJO_MODE=production
      - DB_URL=postgresql://postgres:password@db:5432/registry
      - REGISTRY_SECRET=local-dev-secret-change-in-production
    command: carton exec ./registry minion worker
    depends_on:
      - db
    volumes:
      - ./storage:/app/storage

  scheduler:
    build: .
    environment:
      - MOJO_MODE=production
      - DB_URL=postgresql://postgres:password@db:5432/registry
    command: >
      sh -c "
        while true; do
          carton exec ./registry job attendance_check;
          carton exec ./registry job waitlist_expiration;
          sleep 300;
        done
      "
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: