---
abstract: 'Registration software for events'
author:
  - 'Chris Prather <chris.prather@tamarou.com>'
build_requires:
  Registry::DAO: '0'
  Test::More: '0.88'
  Test::Registry::DB: '0'
  lib: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.043, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Registry
provides:
  Registry:
    file: lib/Registry.pm
    version: '0.001'
requires:
  App::Sqitch: '0'
  Mojo::JSON: '0'
  Mojo::Pg: '0'
  Test::PostgreSQL: '0'
  builtin: '0'
  experimental: '0'
  perl: v5.40.0
  utf8: '0'
version: '0.001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
